#!/bin/sh
# $Id$

# Script to set up environment.

echo "aclocal..."
ACLOCAL=`which aclocal-1.9 || which aclocal19 || which aclocal-1.7 || which aclocal17 || which aclocal-1.5 || which aclocal15 || which aclocal || exit 1`
$ACLOCAL || exit 1

echo "autoheader..."
AUTOHEADER=${AUTOHEADER:-autoheader}
$AUTOHEADER || exit 1

echo "automake..."
AUTOMAKE=`which automake-1.9 || which automake-1.7 || which automake`
#$AUTOMAKE --foreign --add-missing || $AUTOMAKE --gnu --add-missing || exit 1
$AUTOMAKE -a

echo "autoconf..."
AUTOCONF=${AUTOCONF:-autoconf}
$AUTOCONF || exit 1
